version: '3.2'
services:
  php:
    build:
      context: .docker
      dockerfile: Dockerfile
    environment:
      XDEBUG_CONFIG: "remote_host=${XDEBUG_HOST:-docker.for.mac.host.internal} remote_port=${XDEBUG_PORT:-9003} idekey=${XDEBUG_IDEKEY:-PHPSTORM}"
      PHP_IDE_CONFIG: "serverName=Docker"
    working_dir: /var/www
    volumes:
      - ./:/var/www
